language: go
go:
  - 1.7.1
addons:
  apt:
    # we need these to build libalpm (part of pacman)
    packages:
    - asciidoc
    - autopoint
    - libarchive-dev
    - curl
before_install:
  - git clone git://projects.archlinux.org/pacman.git pacman
install: true
script: ./travis_script.sh
